# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/GoldenGMSA" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "Costura.Fody"
        # For Costura.Fody, ignore all updates for version 4
        versions: ["4.x"]
      - dependency-name: "Fody"
        # For Fody, ignore all updates for version 6
        versions: ["6.x"]        
